version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: [ "dependencies" ]
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Berlin"

  # The root pom
  - package-ecosystem: "maven"
    directory: "/src/"
    labels: [ "dependencies" ]
    schedule:
      interval: "daily"
      time: "03:30"
      timezone: "Europe/Berlin"

  # Gomod updates
  - package-ecosystem: "gomod"
    directory: "/src/acceptance/"
    labels: [ "dependencies" ]
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"

  # Gomod updates
  - package-ecosystem: "gomod"
    directory: "/src/autoscaler/"
    labels: [ "dependencies" ]
    schedule:
      interval: "daily"
      time: "04:30"
      timezone: "Europe/Berlin"

  # Gomod updates
  - package-ecosystem: "gomod"
    directory: "/src/changelog/"
    labels: [ "dependencies" ]
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Berlin"

  # Gomod updates
  - package-ecosystem: "gomod"
    directory: "/src/changeloglockcleaner/"
    labels: [ "dependencies" ]
    schedule:
      interval: "daily"
      time: "05:30"
      timezone: "Europe/Berlin"

  # The ASATS app
  - package-ecosystem: "npm"
    directory: "/src/acceptance/assets/app/nodeApp/"
    labels: [ "dependencies" ]
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Berlin"

  # Dependencies update for ci
  - package-ecosystem: "docker"
    directory: "/ci/dockerfiles/autoscaler-deploy"
    labels: [ "dependencies" ]
    schedule:
      interval: "daily"
      time: "06:30"
      timezone: "Europe/Berlin"

  - package-ecosystem: "docker"
    directory: "/ci/dockerfiles/autoscaler-test"
    labels: [ "dependencies" ]
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Berlin"
