---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-deploy
    tag: main

params:
  TARGETS:

inputs:
- name: release
- name: ci

outputs:
- name: release  

run:
  path: ci/ci/autoscaler/tasks/make/make.sh
  args: [ release ]