
- type: remove
  path: /instance_groups/name=nginx/jobs/name=route_registrar/consumes/nats

- type: replace
  path: /instance_groups/name=nginx/jobs/name=route_registrar/consumes/nats-tls?
  value:
    deployment: cf
    from: nats-tls

- type: replace
  path: /releases/-
  value:
    name: bosh-dns-aliases
    version: latest

- type: replace
  path: /releases/name=routing
  value:
    name: routing
    version: latest

- type: replace
  path: /instance_groups/name=nginx/jobs/name=route_registrar/properties/nats?
  value:
    tls:
      enabled: true
      client_cert: ((/bosh-autoscaler/cf/nats_client_cert.certificate))
      client_key: ((/bosh-autoscaler/cf/nats_client_cert.private_key))

- type: replace
  path: /addons?/-
  value:
    name: bosh-dns-aliases
    jobs:
    - name: bosh-dns-aliases
      release: bosh-dns-aliases
      properties:
        aliases:
        - domain: nats.service.cf.internal
          targets:
          - query: '*'
            instance_group: nats
            deployment: cf
            network: default
            domain: bosh
        - domain: _.nats.service.cf.internal
          targets:
          - query: '_'
            instance_group: nats
            deployment: cf
            network: default
            domain: bosh
