---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-release-tools
    tag: main

params:
  NODES: 3
inputs:
- name: app-autoscaler-release
- name: bbl-state

outputs:

run:
  path: app-autoscaler-release/ci/autoscaler/scripts/run-acceptance-tests.sh
