---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-ci-deploy
    tag: master

params:
  SYSTEM_DOMAIN:
  SKIP_SSL_VALIDATION: false
  NAME_PREFIX: ASATS
  NODES: 3
inputs:
- name: bbl-state
- name: app-autoscaler-release

outputs:

run:
  path: app-autoscaler-release/ci/autoscaler/scripts/run-acceptance-tests.sh
