---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ghcr.io/cloudfoundry/app-autoscaler-ci-deploy
    tag: master

params:

inputs:
- name: app-autoscaler-release-main
- name: bbl-state

run:
  path: app-autoscaler-release-main/ci/autoscaler/scripts/update-dns-servers.sh
